---
- hosts: 54.213.210.125 
  user: ec2-user 
  become: yes

  tasks:
  - name: Copying file 
    copy: src=jbs64.tar dest=.
  - name: Extracting Tar File 
    unarchive: src=jbs64.tar  dest=.
  - name: Start jboss Service
    shell: standalone.sh &
    args:
       chdir: ./jbs64/jboss-eap-6.4/bin 
